import './globals.css'
import Link from 'next/link';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="">home</Link>
        <Link href="page-one">page1</Link>
        <Link href="page-two">page2</Link>
        {children}
      </body>
    </html>
  )
}
